// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using Model;
using Model.DB;
using System;

namespace Model.DB.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20171108143131_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("AvatarImage");

                    b.Property<int>("BodyType");

                    b.Property<int?>("CarOwnerCarId");

                    b.Property<long>("CarOwnerID");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<long?>("EquipmentId");

                    b.Property<string>("Manufactor");

                    b.Property<int>("Millage");

                    b.Property<string>("Model");

                    b.Property<int>("MyProperty");

                    b.Property<long?>("PerformanceId");

                    b.Property<long?>("PriceId");

                    b.Property<int>("Year");

                    b.HasKey("CarId");

                    b.HasAlternateKey("CarOwnerID");

                    b.HasIndex("CarOwnerCarId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("PerformanceId");

                    b.HasIndex("PriceId");

                    b.ToTable("Cars");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Car");
                });

            modelBuilder.Entity("Model.Equipment", b =>
                {
                    b.Property<long>("EquipmentId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AC");

                    b.Property<int>("Gearbox");

                    b.Property<bool>("Lift");

                    b.Property<int>("Seats");

                    b.HasKey("EquipmentId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("Model.Performance", b =>
                {
                    b.Property<long>("PerformanceId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("HorsePower");

                    b.Property<int>("MaxSpeed");

                    b.Property<double>("ZeroTo100");

                    b.HasKey("PerformanceId");

                    b.ToTable("Performance");
                });

            modelBuilder.Entity("Model.Price", b =>
                {
                    b.Property<long>("PriceId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("LongTerm");

                    b.Property<decimal>("MidTerm");

                    b.Property<decimal>("ShortTerm");

                    b.HasKey("PriceId");

                    b.ToTable("Price");
                });

            modelBuilder.Entity("Model.Rent", b =>
                {
                    b.Property<long>("RentId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CarId");

                    b.Property<int?>("CarId1");

                    b.Property<int?>("CarOwnerCarId");

                    b.Property<long>("CarOwnerId");

                    b.Property<DateTime>("End");

                    b.Property<DateTime>("Start");

                    b.Property<long>("UserId");

                    b.HasKey("RentId");

                    b.HasIndex("CarId1");

                    b.HasIndex("CarOwnerCarId");

                    b.HasIndex("UserId");

                    b.ToTable("Rents");
                });

            modelBuilder.Entity("Model.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login");

                    b.Property<string>("Mail");

                    b.Property<string>("Password");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Model.CarOwner", b =>
                {
                    b.HasBaseType("Model.Car");


                    b.ToTable("CarOwner");

                    b.HasDiscriminator().HasValue("CarOwner");
                });

            modelBuilder.Entity("Model.Car", b =>
                {
                    b.HasOne("Model.CarOwner", "CarOwner")
                        .WithMany("Cars")
                        .HasForeignKey("CarOwnerCarId");

                    b.HasOne("Model.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId");

                    b.HasOne("Model.Performance", "Performance")
                        .WithMany()
                        .HasForeignKey("PerformanceId");

                    b.HasOne("Model.Price", "Price")
                        .WithMany()
                        .HasForeignKey("PriceId");
                });

            modelBuilder.Entity("Model.Rent", b =>
                {
                    b.HasOne("Model.Car", "Car")
                        .WithMany("Rents")
                        .HasForeignKey("CarId1");

                    b.HasOne("Model.CarOwner", "CarOwner")
                        .WithMany("CarRents")
                        .HasForeignKey("CarOwnerCarId");

                    b.HasOne("Model.User", "User")
                        .WithMany("Rents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
