// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Model;
using Model.DB;
using System;

namespace Model.DB.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20171108154652_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AC");

                    b.Property<byte[]>("AvatarImage");

                    b.Property<int>("BodyType");

                    b.Property<int>("Colour");

                    b.Property<int>("Gearbox");

                    b.Property<int>("HorsePower");

                    b.Property<bool>("Lift");

                    b.Property<decimal>("LongTermPrice");

                    b.Property<string>("Manufactor");

                    b.Property<double>("MaxSpeed");

                    b.Property<decimal>("MidTermPrice");

                    b.Property<int>("Millage");

                    b.Property<string>("Model");

                    b.Property<int>("Seats");

                    b.Property<decimal>("ShortTermPrice");

                    b.Property<long>("UserId");

                    b.Property<int>("Year");

                    b.Property<double>("ZeroTo100");

                    b.HasKey("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Model.Rent", b =>
                {
                    b.Property<long>("RentId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CarId");

                    b.Property<int?>("CarId1");

                    b.Property<DateTime>("End");

                    b.Property<DateTime>("Start");

                    b.Property<long>("UserId");

                    b.HasKey("RentId");

                    b.HasIndex("CarId1");

                    b.HasIndex("UserId");

                    b.ToTable("Rents");
                });

            modelBuilder.Entity("Model.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login");

                    b.Property<string>("Mail");

                    b.Property<string>("Password");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Model.Car", b =>
                {
                    b.HasOne("Model.User", "User")
                        .WithMany("Cars")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Model.Rent", b =>
                {
                    b.HasOne("Model.Car", "Car")
                        .WithMany("Rents")
                        .HasForeignKey("CarId1");

                    b.HasOne("Model.User", "User")
                        .WithMany("Rents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
